server:
  port: 1000
 
spring: 
  application:
    name: atguigu-provider    # 指定当前微服务的名称，以便将来通过微服务名称调用当前微服务时能够找到
  
eureka: 
  client:
    serviceUrl:    # 配置当前微服务作为 Eureka 客户端访问 Eureka 服务器时使用的地址
      defaultZone: http://localhost:5000/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream